project_id = "eijgvnbwbklartrzqhqt"

[functions.analyze-competitors]
verify_jwt = true

[functions.analyze-content-gaps]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.initialize-seo-parameters]
verify_jwt = true
